"use client";

import {useState} from "react";

export default function DemoControlCenter(){
  const [mode,setMode]=useState("smart");
  const nav=["Overview","Studio","Calendar","Inbox","Trends","Analytics","Settings"];
  const trends=[["Bitcoin volatility returns","Market signal · verified","94"],["Memecoin rotation accelerates","Crypto social signal","88"],["Creator economy debate spikes","Cross-platform signal","81"]];
  const drafts=[["X","Bitcoin volatility is back — here’s what changed and what to watch next.","Scheduled · 12:30"],["TikTok","The memecoin cycle is changing faster than most creators realize.","Review · Today"],["X","3 signals worth watching before the next market move.","Draft"]];
  return <main className="page">
    <nav className="productnav">{nav.map((n,i)=><a key={n} href={i===0?"/demo":"/"+n.toLowerCase()}>{n}</a>)}</nav>
    <header className="top"><div className="brand"><div className="mark">C</div><div><strong>CYAN</strong><div className="muted">Social Agent · Control Center</div></div></div><div className="top-actions"><span className="pill">PRO</span><span className="pill">DEMO VIEW</span><span className="status online"><i/> AGENT ONLINE</span></div></header>
    <section className="controlbar"><div><div className="eyebrow">24/7 CLOUD CONTROL</div><div className="hero small">Your social presence, engineered to run.</div><p className="muted">Internal CYAN experience. Demo mode is read-only and requires no login.</p><button className="btn">Pause agent</button></div><div className="mode"><span className="muted">Operation mode</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="conservative">Conservative</option><option value="smart">Smart</option><option value="autonomous">Autonomous</option></select></div></section>
    <section className="card" style={{marginTop:18}}><div className="sectionhead"><div><div className="eyebrow">REMOTE DIAGNOSTICS</div><div className="hero small">Live control-room view of the cloud worker.</div></div><span className="pill ok">ONLINE</span></div><div className="remotegrid" style={{marginTop:14}}>{[["Worker","ONLINE","Heartbeat 12s ago"],["Last tick","12:04:21","Completed successfully"],["Queue","18","scheduled posts"],["Trends","42","signals · 2h"],["Published","27","today"]].map(x=><div className="remoteitem" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small className="muted">{x[2]}</small></div>)}</div></section>
    <section className="statusgrid">{[["Generations","42 / 600","558 remaining"],["Publishes","27 / 500","473 remaining"],["Agent","RUNNING","Cloud worker"],["Scheduler","RUNNING","Due-post runner"],["Trend Watch","RUNNING","Viral detector"],["Heartbeat","12s ago","Last worker signal"]].map(x=><div className="statcard" key={x[0]}><div className="stathead"><span>{x[0]}</span><b className="ok">●</b></div><strong>{x[1]}</strong><span className="muted">{x[2]}</span></div>)}</section>
    <section className="grid"><div className="card"><div className="eyebrow">AI CONTENT ENGINE</div><div className="hero">Turn live stories into platform-native content.</div><p className="muted">Discover → Verify → Score → Generate → Adapt → Review → Schedule → Publish → Analyze.</p><div className="title">Topic / source summary</div><textarea defaultValue="Crypto market story with a useful angle" rows={4}/><button className="btn">Generate content</button></div><div className="card"><div className="eyebrow">PRIORITY ENGINE</div><div className="hero small">Viral events can interrupt flexible schedules.</div><div className="metrics"><div className="metric"><strong>1M+</strong><span>views trigger</span></div><div className="metric"><strong>85+</strong><span>smart interrupt</span></div></div><div className="row"><span>Protected posts</span><span className="pill">LOCKED</span></div><div className="row"><span>Current mode</span><span className="pill">{mode.toUpperCase()}</span></div></div></section>
    <section className="card" style={{marginTop:18}}><div className="sectionhead"><div><div className="eyebrow">LIVE TRENDS</div><div className="hero small">Scored signals detected by the cloud worker.</div></div><span className="pill">FEED ACTIVE</span></div><div className="trendlist" style={{marginTop:14}}>{trends.map(t=><div className="trenditem" key={t[0]}><div><strong>{t[0]}</strong><div className="muted mini">{t[1]}</div></div><span className="pill">{t[2]}</span></div>)}</div></section>
    <section className="card" style={{marginTop:18}}><div className="sectionhead"><div><div className="eyebrow">REMOTE QUEUE</div><div className="title">Scheduled & generated content</div></div><button className="btn ghost">Refresh</button></div><div className="queue" style={{marginTop:10}}>{drafts.map(d=><div className="queueitem" key={d[1]}><div><strong>{d[0]}</strong><div style={{marginTop:6}}>{d[1]}</div><div className="muted mini">{d[2]}</div></div><span className="pill">{d[2].split(" · ")[0].toUpperCase()}</span></div>)}</div></section>
    <section className="card integrations" style={{marginTop:18}}><div className="eyebrow">ACCOUNT CONNECTIONS</div><div className="hero small">Official API connections controlled from one workspace.</div><div className="connectgrid">{["X","Instagram","TikTok","Facebook"].map(p=><div className="connection" key={p}><span className="platformdot">{p[0]}</span><div><strong>{p}</strong><div className="muted">{p==="Instagram"||p==="Facebook"?"Coming next":"Connected · demo"}</div></div><button className="btn ghost" disabled>{p==="Instagram"||p==="Facebook"?"Coming next":"Connected"}</button></div>)}</div></section>
  </main>;
}
