import {NextRequest,NextResponse} from "next/server";
import {consumeUsage,listAgentUsers,releaseUsage,runAsUser} from "@/lib/auth";
import {dueDrafts,getControl,heartbeat,recordEvent,recordWorker,reprioritizeSchedule,saveTrends,updateStatus} from "@/lib/store";
import {publishDraft} from "@/lib/platforms";
import {scoreTrend} from "@/lib/scoring";
import {Trend} from "@/lib/types";
export const dynamic="force-dynamic";
function authorized(req:NextRequest){const secret=process.env.CYAN_WORKER_SECRET||process.env.CRON_SECRET;if(!secret)return process.env.NODE_ENV!=="production";return req.headers.get("authorization")==="Bearer "+secret;}
async function pollGdelt(){const query=process.env.GDELT_TREND_QUERY||"(crypto OR bitcoin OR ethereum OR solana OR memecoin)";const url="https://api.gdeltproject.org/api/v2/doc/doc?query="+encodeURIComponent(query)+"&mode=artlist&format=json&maxrecords=50&timespan=1h";const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(url,{cache:"no-store",headers:{accept:"application/json"},signal:controller.signal});if(!r.ok)throw new Error("GDELT returned "+r.status);const d=await r.json();const articles=Array.isArray(d.articles)?d.articles:[];const now=Date.now();const trends:Trend[]=articles.map((a:any,i:number)=>{const seen=String(a.seendate||"");const parsed=seen.length>=14?Date.parse(seen.slice(0,4)+"-"+seen.slice(4,6)+"-"+seen.slice(6,8)+"T"+seen.slice(8,10)+":"+seen.slice(10,12)+":"+seen.slice(12,14)+"Z"):now;const age=Math.max(0,(now-(Number.isNaN(parsed)?now:parsed))/3600000);const freshness=Math.max(10,100-age*25);const score=scoreTrend({velocity:Math.min(100,100-age*20),engagement:55,freshness,relevance:90,views:0});return{id:"gdelt-"+String(a.url||i),title:String(a.title||"Untitled"),summary:String(a.domain||"Global news")+" · GDELT news momentum",sourceUrl:typeof a.url==="string"?a.url:undefined,score,velocity:Math.min(100,100-age*20),relevance:90,createdAt:new Date().toISOString()};});await saveTrends(trends);return{fetched:trends.length,top:[...trends].sort((a,b)=>b.score-a.score)[0]||null};}finally{clearTimeout(timeout)}}
async function pollTrends(){const url=process.env.TREND_SOURCE_URL;if(!url)return pollGdelt();const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(url,{headers:{accept:"application/json"},cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("Trend source returned "+response.status);const data=await response.json();const items=Array.isArray(data)?data:data.trends;if(!Array.isArray(items))throw new Error("Trend source must return an array or {trends:[]}");const trends:Trend[]=items.slice(0,50).filter((x:any)=>x&&typeof x.title==="string"&&x.title.trim()).map((x:any,i:number)=>{const score=scoreTrend({velocity:Number(x.velocity||0),engagement:Number(x.engagement||0),freshness:Number(x.freshness||0),relevance:Number(x.relevance||0),views:Number(x.views||0)});return{id:String(x.id||(`${Date.now()}-${i}`)),title:x.title.trim(),summary:typeof x.summary==="string"?x.summary:"",sourceUrl:typeof x.sourceUrl==="string"?x.sourceUrl:typeof x.source_url==="string"?x.source_url:undefined,score,views:Number(x.views||0),velocity:Number(x.velocity||0),relevance:Number(x.relevance||0),createdAt:new Date().toISOString()};});await saveTrends(trends);return{fetched:trends.length,top:[...trends].sort((a,b)=>b.score-a.score)[0]||null};}finally{clearTimeout(timeout)}}
async function run(req:NextRequest){if(!authorized(req))return NextResponse.json({error:"Unauthorized worker request"},{status:401});try{const users=await listAgentUsers();const summaries=[];for(const user of users){const result=await runAsUser(user,async()=>{const control=await getControl();await heartbeat();if(control.paused){await recordWorker(true,"Agent paused; tick skipped.");return{paused:true,processed:0,blocked:0,trend:{fetched:0,top:null,interrupted:0}};}let trendResult={fetched:0,top:null as Trend|null,interrupted:0};try{const polled=await pollTrends();trendResult.fetched=polled.fetched;trendResult.top=polled.top;if(polled.top&&control.mode!=="conservative"&&(polled.top.score>=85||(polled.top.views||0)>=1000000)){const changed=await reprioritizeSchedule(polled.top.id,polled.top.score);trendResult.interrupted=changed.changed.length;}}catch{}
const due=await dueDrafts();const results=[];for(const draft of due){const allowed=await consumeUsage(user,"publishes");if(!allowed){await updateStatus(draft.id,"scheduled",new Date(Date.now()+60*60*1000).toISOString());await recordEvent("publish_blocked",{platform:draft.platform,draftId:draft.id,metadata:{reason:"daily_plan_limit"}});results.push({id:draft.id,platform:draft.platform,ok:false,message:"Daily publish limit reached for this plan."});continue;}const published=await publishDraft(draft);if(published.ok){await updateStatus(draft.id,"published");await recordEvent("publish",{platform:draft.platform,draftId:draft.id,externalId:published.externalId});}else{await releaseUsage(user,"publishes");await updateStatus(draft.id,"scheduled",new Date(Date.now()+15*60*1000).toISOString());await recordEvent("publish_failed",{platform:draft.platform,draftId:draft.id,metadata:{message:published.message}});}results.push({id:draft.id,platform:draft.platform,ok:published.ok,message:published.message});}const processed=results.filter(r=>r.ok).length,blocked=results.filter(r=>!r.ok).length;await recordWorker(blocked===0,"Trends="+trendResult.fetched+"; due="+due.length+"; published="+processed+"; blocked="+blocked+"; interrupted="+trendResult.interrupted);return{paused:false,processed,blocked,trend:trendResult};});summaries.push({workspace:user.id,email:user.email,plan:user.plan,...result});}return NextResponse.json({ok:true,workspaces:summaries.length,summaries,heartbeat:new Date().toISOString()});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Worker tick failed"},{status:500});}}
export async function GET(req:NextRequest){return run(req)}
export async function POST(req:NextRequest){return run(req)}
