"use client";
import {useState} from "react";
type Draft={platform:string;content:string;angle:string};
export default function Home(){
 const [topic,setTopic]=useState("Crypto market story with a useful angle"),[loading,setLoading]=useState(false),[drafts,setDrafts]=useState<Draft[]>([]),[manual,setManual]=useState(""),[manualPlatform,setManualPlatform]=useState("X"),[scheduled,setScheduled]=useState(""),[error,setError]=useState("");
 async function generate(){setLoading(true);setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Generation failed");setDrafts(d.drafts)}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}}
 async function saveManual(){setError("");try{const r=await fetch("/api/manual",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content:manual,platform:manualPlatform,scheduledAt:scheduled||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error);setManual("");}catch(e){setError(e instanceof Error?e.message:"Could not save post")}}
 return <main className="page">
 <header className="top"><div className="brand"><div className="mark">C</div><div><strong>CYAN</strong><div className="muted">Social Agent</div></div></div><span className="pill">PUBLIC SAAS · HUMAN CONTROL</span></header>
 <section className="grid">
  <div className="card"><div className="eyebrow">AI CONTENT ENGINE</div><div className="hero">Turn live stories into platform-native content.</div><p className="muted">Discover → Verify → Score → Generate → Adapt → Review → Schedule → Publish → Analyze.</p><div className="title">Topic / source summary</div><textarea value={topic} onChange={e=>setTopic(e.target.value)} rows={5} style={{width:"100%",marginTop:8,background:"#06101d",color:"#eaf2ff",border:"1px solid #19304d",borderRadius:12,padding:14}}/><button className="btn" style={{marginTop:12}} onClick={generate} disabled={loading}>{loading?"Generating…":"Generate content"}</button></div>
  <div className="card"><div className="eyebrow">PRIORITY ENGINE</div><div className="hero small">Viral events can interrupt flexible schedules.</div><div className="metric"><strong>1M+</strong><span>views trigger</span></div><div className="metric"><strong>90</strong><span>viral score</span></div><div className="row"><span>Protected posts</span><span className="pill">LOCKED</span></div><div className="row"><span>Scheduler</span><span className="pill">SMART MODE</span></div></div>
 </section>
 <section className="card" style={{marginTop:18}}><div className="eyebrow">MANUAL POST</div><div className="hero small">Write your own post, save it, and let CYAN publish it on schedule.</div><div className="controls"><select value={manualPlatform} onChange={e=>setManualPlatform(e.target.value)}><option>X</option><option>Instagram</option><option>Facebook</option><option>TikTok</option></select><input type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)}/></div><textarea value={manual} onChange={e=>setManual(e.target.value)} placeholder="Write a post…" rows={4} style={{width:"100%",marginTop:10,background:"#06101d",color:"#eaf2ff",border:"1px solid #19304d",borderRadius:12,padding:14}}/><button className="btn secondary" style={{marginTop:10}} onClick={saveManual}>Save to calendar</button></section>
 <section className="card" style={{marginTop:18}}><div className="title">Generated queue</div>{error&&<div className="error">{error}</div>}<div className="queue" style={{marginTop:10}}>{drafts.length===0?<div className="muted">No AI drafts yet.</div>:drafts.map((d,i)=><div className="queueitem" key={i}><div><strong>{d.platform}</strong><div style={{marginTop:6}}>{d.content}</div></div><span className="pill">{d.angle}</span></div>)}</div></section>
 </main>;
}