import {Draft,QueueStatus,PriorityMode,Trend} from "./types";
import {dbReady,pool} from "./db";
import {limits,workspaceId} from "./auth";

function rowToDraft(r:any):Draft{
 return {id:r.id,platform:r.platform,angle:r.angle,content:r.content,status:r.status,scheduledAt:r.scheduled_at?new Date(r.scheduled_at).toISOString():undefined,trendId:r.trend_id||undefined,protected:Boolean(r.protected),mediaUrl:r.media_url||undefined,mediaType:r.media_type||undefined,externalId:r.external_id||undefined};
}

export async function listDrafts():Promise<Draft[]>{
 await dbReady(); const r=await pool.query("SELECT * FROM cyan_drafts WHERE workspace_id=$1 ORDER BY COALESCE(scheduled_at, created_at) ASC, created_at DESC",[workspaceId()]); return r.rows.map(rowToDraft);
}
export async function saveDrafts(drafts:Draft[]){
 await dbReady();
 for(const d of drafts){await pool.query(`INSERT INTO cyan_drafts(id,workspace_id,platform,angle,content,status,scheduled_at,trend_id,protected,media_url,media_type,external_id)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
 ON CONFLICT(id) DO UPDATE SET content=EXCLUDED.content,status=EXCLUDED.status,scheduled_at=EXCLUDED.scheduled_at,trend_id=EXCLUDED.trend_id,protected=EXCLUDED.protected,media_url=EXCLUDED.media_url,media_type=EXCLUDED.media_type,external_id=EXCLUDED.external_id`,[d.id,workspaceId(),d.platform,d.angle,d.content,d.status,d.scheduledAt||null,d.trendId||null,Boolean(d.protected),d.mediaUrl||null,d.mediaType||null,d.externalId||null]);}
 return drafts;
}
export async function addManualDraft(draft:Draft){await saveDrafts([draft]);return draft;}
export async function updateStatus(id:string,status:QueueStatus,scheduledAt?:string,externalId?:string|null){await dbReady();const r=await pool.query("UPDATE cyan_drafts SET status=$1, scheduled_at=$2, external_id=$3 WHERE id=$4 AND workspace_id=$5 RETURNING *",[status,scheduledAt||null,externalId===undefined?null:externalId,id,workspaceId()]);return r.rows[0]?rowToDraft(r.rows[0]):undefined;}
export async function saveTrends(trends:Trend[]){await dbReady();for(const t of trends){await pool.query(`INSERT INTO cyan_trends(id,workspace_id,title,summary,source_url,score,views,velocity,relevance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,summary=EXCLUDED.summary,source_url=EXCLUDED.source_url,score=EXCLUDED.score,views=EXCLUDED.views,velocity=EXCLUDED.velocity,relevance=EXCLUDED.relevance`,[t.id,workspaceId(),t.title,t.summary,t.sourceUrl||null,t.score,t.views||null,t.velocity||null,t.relevance||null]);}return trends;}
export async function latestTrends(limit=20):Promise<Trend[]>{await dbReady();const r=await pool.query("SELECT id,title,summary,source_url,score,views,velocity,relevance,created_at FROM cyan_trends WHERE workspace_id=$1 ORDER BY score DESC, created_at DESC LIMIT $2",[workspaceId(),limit]);return r.rows.map((x:any)=>({id:x.id,title:x.title,summary:x.summary,sourceUrl:x.source_url||undefined,score:Number(x.score),views:x.views?Number(x.views):undefined,velocity:x.velocity?Number(x.velocity):undefined,relevance:x.relevance?Number(x.relevance):undefined,createdAt:new Date(x.created_at).toISOString()}));}
export async function claimDueDrafts(now=new Date()){await dbReady();const client=await pool.connect();try{await client.query("BEGIN");const selected=await client.query("SELECT id FROM cyan_drafts WHERE workspace_id=$1 AND status='scheduled' AND scheduled_at <= $2 ORDER BY scheduled_at ASC FOR UPDATE SKIP LOCKED LIMIT 20",[workspaceId(),now.toISOString()]);if(selected.rows.length===0){await client.query("COMMIT");return [];}const ids=selected.rows.map((x:any)=>x.id);const updated=await client.query("UPDATE cyan_drafts SET status='publishing' WHERE workspace_id=$1 AND id=ANY($2::text[]) RETURNING *",[workspaceId(),ids]);await client.query("COMMIT");return updated.rows.map(rowToDraft);}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
export async function recoverStalePublishing(now=new Date()){
 await dbReady();
 const cutoff=new Date(now.getTime()-15*60*1000).toISOString();
 const r=await pool.query(`UPDATE cyan_drafts SET status='scheduled',scheduled_at=$1
  WHERE workspace_id=$2 AND status='publishing' AND scheduled_at IS NOT NULL AND scheduled_at <= $3
  RETURNING id`,[now.toISOString(),workspaceId(),cutoff]);
 return r.rowCount||0;
}
export async function dueDrafts(now=new Date()){return claimDueDrafts(now);}
export async function setControl(patch:{mode?:PriorityMode;paused?:boolean}){await dbReady();const current=await getControl();const mode=patch.mode||current.mode;const paused=patch.paused===undefined?current.paused:patch.paused;await pool.query(`INSERT INTO cyan_control(workspace_id,mode,paused,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(workspace_id) DO UPDATE SET mode=EXCLUDED.mode,paused=EXCLUDED.paused,updated_at=NOW()`,[workspaceId(),mode,paused]);return {...current,mode,paused};}
export async function getControl(){await dbReady();const r=await pool.query("SELECT mode,paused,heartbeat_at FROM cyan_control WHERE workspace_id=$1",[workspaceId()]);if(!r.rows[0])return {mode:"smart" as PriorityMode,paused:false,heartbeatAt:null as string|null};return {mode:r.rows[0].mode as PriorityMode,paused:Boolean(r.rows[0].paused),heartbeatAt:r.rows[0].heartbeat_at?new Date(r.rows[0].heartbeat_at).toISOString():null};}
export async function heartbeat(){await dbReady();await pool.query(`INSERT INTO cyan_control(workspace_id,mode,paused,heartbeat_at,updated_at) VALUES($1,'smart',false,NOW(),NOW()) ON CONFLICT(workspace_id) DO UPDATE SET heartbeat_at=NOW(),updated_at=NOW()`,[workspaceId()]);}
export async function recordWorker(ok:boolean,detail:string){await dbReady();await pool.query("INSERT INTO cyan_worker_runs(workspace_id,ok,detail) VALUES($1,$2,$3)",[workspaceId(),ok,detail]);}
export async function latestWorkerRun(){await dbReady();const r=await pool.query("SELECT ran_at,ok,detail FROM cyan_worker_runs WHERE workspace_id=$1 ORDER BY ran_at DESC LIMIT 1",[workspaceId()]);return r.rows[0]?{ranAt:new Date(r.rows[0].ran_at).toISOString(),ok:Boolean(r.rows[0].ok),detail:String(r.rows[0].detail)}:null;}
export async function reprioritizeSchedule(trendId:string,viralScore:number,now=new Date()){await dbReady();const movable=await pool.query(`SELECT * FROM cyan_drafts WHERE workspace_id=$1 AND status='scheduled' AND protected=false AND scheduled_at IS NOT NULL AND scheduled_at >= $2 ORDER BY scheduled_at ASC LIMIT 4`,[workspaceId(),now.toISOString()]);if(viralScore<85||movable.rows.length===0)return {changed:[],message:"No interruption required.",trendId};const changed:Draft[]=[];let cursor=new Date(now.getTime()+15*60*1000);for(const r of movable.rows){const next=cursor.toISOString();const u=await pool.query("UPDATE cyan_drafts SET scheduled_at=$1 WHERE id=$2 AND workspace_id=$3 RETURNING *",[next,r.id,workspaceId()]);if(u.rows[0])changed.push(rowToDraft(u.rows[0]));cursor=new Date(cursor.getTime()+90*60*1000);}return {changed,message:"Flexible scheduled posts moved to make room for the viral priority slot.",trendId};}
export async function disconnectConnection(platform:string){await dbReady();await pool.query("DELETE FROM cyan_connections WHERE workspace_id=$1 AND platform=$2",[workspaceId(),platform]);}\nexport async function listConnections(){await dbReady();const r=await pool.query("SELECT platform,status,account_label,connected_at FROM cyan_connections WHERE workspace_id=$1 ORDER BY platform",[workspaceId()]);return r.rows.map((x:any)=>({platform:x.platform,status:x.status,accountLabel:x.account_label||undefined,connectedAt:x.connected_at?new Date(x.connected_at).toISOString():undefined}));}
export async function saveConnection(platform:string,accessTokenEnc:string,refreshTokenEnc:string,accountLabel?:string){await dbReady();const planRow=await pool.query("SELECT plan FROM cyan_users WHERE id=$1",[workspaceId()]);const plan=planRow.rows[0]?.plan||"free";const existing=await pool.query("SELECT 1 FROM cyan_connections WHERE workspace_id=$1 AND platform=$2",[workspaceId(),platform]);if(existing.rowCount===0){const count=await pool.query("SELECT COUNT(*)::int AS count FROM cyan_connections WHERE workspace_id=$1 AND status='connected'",[workspaceId()]);if(Number(count.rows[0]?.count||0)>=limits(plan).accounts)throw new Error("Account limit reached for your plan.");}await pool.query(`INSERT INTO cyan_connections(workspace_id,platform,status,account_label,access_token_enc,refresh_token_enc,connected_at) VALUES($1,$2,'connected',$3,$4,$5,NOW()) ON CONFLICT(workspace_id,platform) DO UPDATE SET status='connected',account_label=EXCLUDED.account_label,access_token_enc=EXCLUDED.access_token_enc,refresh_token_enc=EXCLUDED.refresh_token_enc,connected_at=NOW()`,[workspaceId(),platform,accountLabel||null,accessTokenEnc,refreshTokenEnc]);}
export async function getConnectionSecret(platform:string){await dbReady();const r=await pool.query("SELECT access_token_enc,refresh_token_enc,account_label,status FROM cyan_connections WHERE workspace_id=$1 AND platform=$2",[workspaceId(),platform]);return r.rows[0]||null;}
export async function updateConnectionTokens(platform:string,accessTokenEnc:string,refreshTokenEnc?:string){await dbReady();await pool.query("UPDATE cyan_connections SET access_token_enc=$1, refresh_token_enc=COALESCE($2,refresh_token_enc), status='connected' WHERE workspace_id=$3 AND platform=$4",[accessTokenEnc,refreshTokenEnc||null,workspaceId(),platform]);}
export async function recordEvent(type:string,data:{platform?:string;draftId?:string;externalId?:string;metadata?:Record<string,unknown>}={}){await dbReady();await pool.query("INSERT INTO cyan_events(workspace_id,type,platform,draft_id,external_id,metadata) VALUES($1,$2,$3,$4,$5,$6)",[workspaceId(),type,data.platform||null,data.draftId||null,data.externalId||null,JSON.stringify(data.metadata||{})]);}
export async function analyticsSummary(){await dbReady();const r=await pool.query("SELECT type,platform,COUNT(*)::int AS count FROM cyan_events WHERE workspace_id=$1 AND created_at>=NOW()-INTERVAL '30 days' GROUP BY type,platform ORDER BY count DESC",[workspaceId()]);return r.rows;}
