import {Draft,QueueStatus,PriorityMode,Trend} from "./types";
import {dbReady,pool} from "./db";
import {limits,workspaceId} from "./auth";
import {classifyContent} from "./content-intelligence";
import {assertMutableDraft} from "./lifecycle-audit";

function rowToDraft(r:any):Draft{return{id:r.id,platform:r.platform,angle:r.angle,content:r.content,status:r.status,scheduledAt:r.scheduled_at?new Date(r.scheduled_at).toISOString():undefined,trendId:r.trend_id||undefined,protected:Boolean(r.protected),mediaUrl:r.media_url||undefined,mediaType:r.media_type||undefined,externalId:r.external_id||undefined,publishAttempts:Number(r.publish_attempts||0),publishStartedAt:r.publish_started_at?new Date(r.publish_started_at).toISOString():undefined,features:r.features&&Object.keys(r.features).length?r.features:undefined,experimentId:r.experiment_id||undefined,variant:r.variant||undefined,exploration:Boolean(r.exploration)};}
export async function getDraft(id:string):Promise<Draft|undefined>{await dbReady();const r=await pool.query("SELECT * FROM cyan_drafts WHERE workspace_id=$1 AND id=$2 LIMIT 1",[workspaceId(),id]);return r.rows[0]?rowToDraft(r.rows[0]):undefined;}
export async function listDrafts():Promise<Draft[]>{await dbReady();const r=await pool.query("SELECT * FROM cyan_drafts WHERE workspace_id=$1 ORDER BY COALESCE(scheduled_at,created_at) ASC,created_at DESC",[workspaceId()]);return r.rows.map(rowToDraft);}
export async function contentFatigue(drafts:Draft[]){await dbReady();const r=await pool.query("SELECT platform,content FROM cyan_drafts WHERE workspace_id=$1 AND created_at>=NOW()-INTERVAL '30 days' ORDER BY created_at DESC LIMIT 100",[workspaceId()]);const normalize=(s:string)=>new Set(s.toLowerCase().replace(/https?:\/\/\S+/g," ").replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(w=>w.length>2));const similarity=(a:Set<string>,b:Set<string>)=>{let hit=0;for(const x of a)if(b.has(x))hit++;return hit/Math.max(1,Math.min(a.size,b.size));};return drafts.filter(d=>!r.rows.some((x:any)=>String(x.platform)===d.platform&&similarity(normalize(d.content),normalize(String(x.content||"")))>0.82));}
export async function saveDrafts(drafts:Draft[]){await dbReady();for(const d of drafts){const existing=await pool.query("SELECT status,protected FROM cyan_drafts WHERE workspace_id=$1 AND id=$2 LIMIT 1",[workspaceId(),d.id]);if(existing.rowCount)await assertMutableDraft(d.id);const features=d.features||classifyContent(d.content,d.platform,d.mediaType);await pool.query(`INSERT INTO cyan_drafts(id,workspace_id,platform,angle,content,status,scheduled_at,trend_id,protected,media_url,media_type,external_id,publish_attempts,publish_started_at,features,experiment_id,variant,exploration) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT(id) DO UPDATE SET content=EXCLUDED.content,status=EXCLUDED.status,scheduled_at=EXCLUDED.scheduled_at,trend_id=EXCLUDED.trend_id,protected=EXCLUDED.protected,media_url=EXCLUDED.media_url,media_type=EXCLUDED.media_type,external_id=EXCLUDED.external_id,publish_attempts=EXCLUDED.publish_attempts,publish_started_at=EXCLUDED.publish_started_at,features=EXCLUDED.features,experiment_id=EXCLUDED.experiment_id,variant=EXCLUDED.variant,exploration=EXCLUDED.exploration WHERE cyan_drafts.status NOT IN ('published') AND cyan_drafts.protected=false`,[d.id,workspaceId(),d.platform,d.angle,d.content,d.status,d.scheduledAt||null,d.trendId||null,Boolean(d.protected),d.mediaUrl||null,d.mediaType||null,d.externalId||null,Number(d.publishAttempts||0),d.publishStartedAt||null,JSON.stringify(features),d.experimentId||null,d.variant||null]);}return drafts;}
export async function addManualDraft(draft:Draft){await saveDrafts([draft]);return draft;}
export async function updateStatus(id:string,status:QueueStatus,scheduledAt?:string,externalId?:string|null){await assertMutableDraft(id);await dbReady();const r=await pool.query(`UPDATE cyan_drafts SET status=$1,scheduled_at=$2,external_id=CASE WHEN $3::boolean THEN $4 ELSE external_id END,publish_attempts=CASE WHEN $1='publishing' THEN publish_attempts+1 WHEN $1='published' OR $4::text IS NULL THEN publish_attempts ELSE publish_attempts END,publish_started_at=CASE WHEN $1='publishing' THEN NOW() WHEN $1 IN ('published','review','draft') THEN NULL WHEN $4::text IS NULL THEN NULL ELSE publish_started_at END WHERE id=$5 AND workspace_id=$6 AND status NOT IN ('published') AND protected=false RETURNING *`,[status,scheduledAt||null,externalId!==undefined,externalId===undefined?null:externalId,id,workspaceId()]);return r.rows[0]?rowToDraft(r.rows[0]):undefined;}
export async function updateStatusesAtomic(ids:string[],status:QueueStatus,scheduledAtFor:(index:number)=>string|undefined){await dbReady();const client=await pool.connect();try{await client.query("BEGIN");const locked=await client.query("SELECT id,status,protected FROM cyan_drafts WHERE workspace_id=$1 AND id=ANY($2::text[]) FOR UPDATE",[workspaceId(),ids]);if(locked.rowCount!==ids.length||locked.rows.some((r:any)=>r.status==='published'||r.protected))throw new Error("One or more selected drafts are no longer mutable.");const updated:any[]=[];for(let i=0;i<ids.length;i++){const r=await client.query(`UPDATE cyan_drafts SET status=$1,scheduled_at=$2,publish_started_at=CASE WHEN $1 IN ('review','draft') THEN NULL ELSE publish_started_at END WHERE workspace_id=$3 AND id=$4 AND status NOT IN ('published') AND protected=false RETURNING *`,[status,scheduledAtFor(i),workspaceId(),ids[i]]);if(!r.rows[0])throw new Error("Bulk update could not be completed safely.");updated.push(rowToDraft(r.rows[0]));}await client.query("COMMIT");return updated;}catch(e){await client.query("ROLLBACK");throw e}finally{client.release();}}
export async function saveTrends(trends:Trend[]){await dbReady();for(const t of trends){await pool.query(`INSERT INTO cyan_trends(id,workspace_id,title,summary,source_url,score,views,velocity,relevance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,summary=EXCLUDED.summary,source_url=EXCLUDED.source_url,score=EXCLUDED.score,views=EXCLUDED.views,velocity=EXCLUDED.velocity,relevance=EXCLUDED.relevance`,[t.id,workspaceId(),t.title,t.summary,t.sourceUrl||null,t.score,t.views||null,t.velocity||null,t.relevance||null]);}return trends;}
export async function latestTrends(limit=20):Promise<Trend[]>{await dbReady();const r=await pool.query("SELECT id,title,summary,source_url,score,views,velocity,relevance,created_at FROM cyan_trends WHERE workspace_id=$1 ORDER BY score DESC,created_at DESC LIMIT $2",[workspaceId(),limit]);return r.rows.map((x:any)=>({id:x.id,title:x.title,summary:x.summary,sourceUrl:x.source_url||undefined,score:Number(x.score),views:x.views?Number(x.views):undefined,velocity:x.velocity?Number(x.velocity):undefined,relevance:x.relevance?Number(x.relevance):undefined,createdAt:new Date(x.created_at).toISOString()}));}
export async function claimManualPublish(id:string){await dbReady();const r=await pool.query(`UPDATE cyan_drafts SET status='publishing',publish_attempts=publish_attempts+1,publish_started_at=NOW() WHERE workspace_id=$1 AND id=$2 AND status IN ('draft','review','scheduled') AND protected=false AND (approval_status IN ('approved','not_required') OR approval_status IS NULL) RETURNING *`,[workspaceId(),id]);return r.rows[0]?rowToDraft(r.rows[0]):undefined;}
export async function claimDueDrafts(now=new Date()){await dbReady();const client=await pool.connect();try{await client.query("BEGIN");const selected=await client.query("SELECT id FROM cyan_drafts WHERE workspace_id=$1 AND status='scheduled' AND protected=false AND scheduled_at <= $2 AND (approval_status IN ('approved','not_required') OR approval_status IS NULL) ORDER BY scheduled_at ASC FOR UPDATE SKIP LOCKED LIMIT 20",[workspaceId(),now.toISOString()]);if(!selected.rows.length){await client.query("COMMIT");return [];}const ids=selected.rows.map((x:any)=>x.id);const updated=await client.query("UPDATE cyan_drafts SET status='publishing',publish_attempts=publish_attempts+1,publish_started_at=NOW() WHERE workspace_id=$1 AND id=ANY($2::text[]) RETURNING *",[workspaceId(),ids]);await client.query("COMMIT");return updated.rows.map(rowToDraft);}catch(e){await client.query("ROLLBACK");throw e}finally{client.release();}}
export async function recoverStalePublishing(now=new Date()){await dbReady();const cutoff=new Date(now.getTime()-15*60*1000).toISOString();const r=await pool.query(`UPDATE cyan_drafts SET status=CASE WHEN external_id IS NULL AND scheduled_at IS NULL THEN 'review' ELSE 'scheduled' END,scheduled_at=CASE WHEN external_id IS NULL AND scheduled_at IS NULL THEN NULL ELSE $1 END,publish_started_at=NULL WHERE workspace_id=$2 AND status='publishing' AND protected=false AND publish_started_at IS NOT NULL AND publish_started_at <= $3 RETURNING id,status`,[now.toISOString(),workspaceId(),cutoff]);return r.rowCount||0;}
export async function dueDrafts(now=new Date()){return claimDueDrafts(now);}
export async function setControl(patch:{mode?:PriorityMode;paused?:boolean;timezone?:string}){await dbReady();const current=await getControl();const mode=patch.mode||current.mode,paused=patch.paused===undefined?current.paused:patch.paused,timezone=patch.timezone||current.timezone;await pool.query(`INSERT INTO cyan_control(workspace_id,mode,paused,timezone,updated_at) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(workspace_id) DO UPDATE SET mode=EXCLUDED.mode,paused=EXCLUDED.paused,timezone=EXCLUDED.timezone,updated_at=NOW()`,[workspaceId(),mode,paused,timezone]);return{...current,mode,paused,timezone};}
export async function getControl(){await dbReady();const r=await pool.query("SELECT mode,paused,timezone,heartbeat_at,approval_required FROM cyan_control WHERE workspace_id=$1",[workspaceId()]);if(!r.rows[0])return{mode:"smart" as PriorityMode,paused:false,timezone:"Asia/Jakarta",heartbeatAt:null as string|null,approvalRequired:false};return{mode:r.rows[0].mode as PriorityMode,paused:Boolean(r.rows[0].paused),timezone:String(r.rows[0].timezone||"Asia/Jakarta"),heartbeatAt:r.rows[0].heartbeat_at?new Date(r.rows[0].heartbeat_at).toISOString():null,approvalRequired:Boolean(r.rows[0].approval_required)};}
export async function setControl(patch:{mode?:PriorityMode;paused?:boolean;timezone?:string;approvalRequired?:boolean}){await dbReady();const current=await getControl();const mode=patch.mode??current.mode,paused=patch.paused??current.paused,timezone=patch.timezone??current.timezone,approvalRequired=patch.approvalRequired??current.approvalRequired;const r=await pool.query(`INSERT INTO cyan_control(workspace_id,mode,paused,timezone,approval_required,updated_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT(workspace_id) DO UPDATE SET mode=EXCLUDED.mode,paused=EXCLUDED.paused,timezone=EXCLUDED.timezone,approval_required=EXCLUDED.approval_required,updated_at=NOW() RETURNING mode,paused,timezone,approval_required`,[workspaceId(),mode,paused,timezone,approvalRequired]);return{...r.rows[0],approvalRequired:Boolean(r.rows[0].approval_required)};}
export async function heartbeat(){await dbReady();await pool.query(`INSERT INTO cyan_control(workspace_id,mode,paused,heartbeat_at,updated_at) VALUES($1,'smart',false,NOW(),NOW()) ON CONFLICT(workspace_id) DO UPDATE SET heartbeat_at=NOW(),updated_at=NOW()`,[workspaceId()]);}
export async function recordWorker(ok:boolean,detail:string){await dbReady();await pool.query("INSERT INTO cyan_worker_runs(workspace_id,ok,detail) VALUES($1,$2,$3)",[workspaceId(),ok,detail]);}
export async function latestWorkerRun(){await dbReady();const r=await pool.query("SELECT ran_at,ok,detail FROM cyan_worker_runs WHERE workspace_id=$1 ORDER BY ran_at DESC LIMIT 1",[workspaceId()]);return r.rows[0]?{ranAt:new Date(r.rows[0].ran_at).toISOString(),ok:Boolean(r.rows[0].ok),detail:String(r.rows[0].detail)}:null;}
export async function reprioritizeSchedule(trendId:string,viralScore:number,now=new Date()){await dbReady();const movable=await pool.query(`SELECT * FROM cyan_drafts WHERE workspace_id=$1 AND status='scheduled' AND protected=false AND scheduled_at IS NOT NULL AND scheduled_at >= $2 ORDER BY scheduled_at ASC LIMIT 4`,[workspaceId(),now.toISOString()]);if(viralScore<85||!movable.rows.length)return{changed:[],message:"No interruption required.",trendId};const changed:Draft[]=[];let cursor=new Date(now.getTime()+15*60*1000);for(const r of movable.rows){const u=await pool.query("UPDATE cyan_drafts SET scheduled_at=$1 WHERE id=$2 AND workspace_id=$3 AND status='scheduled' AND protected=false RETURNING *",[cursor.toISOString(),r.id,workspaceId()]);if(u.rows[0])changed.push(rowToDraft(u.rows[0]));cursor=new Date(cursor.getTime()+90*60*1000);}return{changed,message:"Flexible scheduled posts moved to make room for the viral priority slot.",trendId};}
export async function disconnectConnection(platform:string){await dbReady();await pool.query("DELETE FROM cyan_connections WHERE workspace_id=$1 AND platform=$2",[workspaceId(),platform]);}
export async function listConnections(){await dbReady();const r=await pool.query("SELECT platform,status,account_label,connected_at FROM cyan_connections WHERE workspace_id=$1 ORDER BY platform",[workspaceId()]);return r.rows.map((x:any)=>({platform:x.platform,status:x.status,accountLabel:x.account_label||undefined,connectedAt:x.connected_at?new Date(x.connected_at).toISOString():undefined}));}
export async function saveConnection(platform:string,accessTokenEnc:string,refreshTokenEnc:string,accountLabel?:string){await dbReady();const planRow=await pool.query("SELECT plan FROM cyan_users WHERE id=$1",[workspaceId()]);const plan=planRow.rows[0]?.plan||"free";const existing=await pool.query("SELECT 1 FROM cyan_connections WHERE workspace_id=$1 AND platform=$2",[workspaceId(),platform]);if(!existing.rowCount){const count=await pool.query("SELECT COUNT(*)::int AS count FROM cyan_connections WHERE workspace_id=$1 AND status='connected'",[workspaceId()]);if(Number(count.rows[0]?.count||0)>=limits(plan).accounts)throw new Error("Account limit reached for your plan.");}await pool.query(`INSERT INTO cyan_connections(workspace_id,platform,status,account_label,access_token_enc,refresh_token_enc,connected_at) VALUES($1,$2,'connected',$3,$4,$5,NOW()) ON CONFLICT(workspace_id,platform) DO UPDATE SET status='connected',account_label=EXCLUDED.account_label,access_token_enc=EXCLUDED.access_token_enc,refresh_token_enc=EXCLUDED.refresh_token_enc,connected_at=NOW()`,[workspaceId(),platform,accountLabel||null,accessTokenEnc,refreshTokenEnc]);}
export async function getConnectionSecret(platform:string){await dbReady();const r=await pool.query("SELECT access_token_enc,refresh_token_enc,account_label,status FROM cyan_connections WHERE workspace_id=$1 AND platform=$2",[workspaceId(),platform]);return r.rows[0]||null;}
export async function updateConnectionTokens(platform:string,accessTokenEnc:string,refreshTokenEnc?:string){await dbReady();await pool.query("UPDATE cyan_connections SET access_token_enc=$1,refresh_token_enc=COALESCE($2,refresh_token_enc),status='connected' WHERE workspace_id=$3 AND platform=$4",[accessTokenEnc,refreshTokenEnc||null,workspaceId(),platform]);}
export async function recordEvent(type:string,data:{platform?:string;draftId?:string;externalId?:string;metadata?:Record<string,unknown>}={}){await dbReady();await pool.query("INSERT INTO cyan_events(workspace_id,type,platform,draft_id,external_id,metadata) VALUES($1,$2,$3,$4,$5,$6)",[workspaceId(),type,data.platform||null,data.draftId||null,data.externalId||null,JSON.stringify(data.metadata||{})]);}
export async function learningSignals(){await dbReady();const r=await pool.query(`SELECT COALESCE(platform,'unknown') AS platform,COUNT(*) FILTER (WHERE type='publish')::int AS published,COUNT(*) FILTER (WHERE type='publish_failed')::int AS failed,COUNT(*) FILTER (WHERE type='content_feedback')::int AS feedback FROM cyan_events WHERE workspace_id=$1 AND created_at>=NOW()-INTERVAL '30 days' GROUP BY platform ORDER BY published DESC,feedback DESC`,[workspaceId()]);return r.rows.map((x:any)=>({platform:String(x.platform),published:Number(x.published||0),failed:Number(x.failed||0),feedback:Number(x.feedback||0)}));}
export async function analyticsSummary(){await dbReady();const r=await pool.query("SELECT type,platform,COUNT(*)::int AS count FROM cyan_events WHERE workspace_id=$1 AND created_at>=NOW()-INTERVAL '30 days' GROUP BY type,platform ORDER BY count DESC",[workspaceId()]);return r.rows;}
export async function contentIntelligenceSummary(){await dbReady();const [features,experiments]=await Promise.all([pool.query("SELECT features,platform,angle,COUNT(*)::int AS count FROM cyan_drafts WHERE workspace_id=$1 AND created_at>=NOW()-INTERVAL '30 days' GROUP BY features,platform,angle ORDER BY count DESC LIMIT 50",[workspaceId()]),pool.query("SELECT id,topic,status,created_at,winner_draft_id,winner_score FROM cyan_experiments WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT 20",[workspaceId()])]);return{features:features.rows,experiments:experiments.rows};}
