"use client";
import {useEffect,useState} from "react";
type Control={mode:"conservative"|"smart"|"autonomous";paused:boolean;timezone:string};
type Connection={platform:string;status:string;accountLabel?:string}; type Plan={id:string;name:string;price:number;generations:number;publishes:number;accounts:number}; type Usage={plan:string;limits:{generations:number;publishes:number;accounts:number};used:{generations:number;publishes:number}};
export default function Settings(){
 const [control,setControl]=useState<Control>({mode:"smart",paused:false,timezone:"Asia/Jakarta"});
 const [connections,setConnections]=useState<Connection[]>([]);
 const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [plans,setPlans]=useState<Plan[]>([]); const [usage,setUsage]=useState<Usage|null>(null); const [billing,setBilling]=useState(false);
 async function load(){try{const [a,b,p,v]=await Promise.all([fetch("/api/control",{cache:"no-store"}),fetch("/api/connections",{cache:"no-store"}),fetch("/api/billing/plans",{cache:"no-store"}),fetch("/api/billing/usage",{cache:"no-store"})]);const ad=await a.json(),bd=await b.json();if(a.ok)setControl({mode:ad.mode||"smart",paused:Boolean(ad.paused),timezone:ad.timezone||"Asia/Jakarta"});if(b.ok)setConnections(bd.connections||[]); if(p.ok){const pd=await p.json();setPlans(pd.plans||[])} if(v.ok)setUsage(await v.json()); }catch{setError("Could not load workspace settings.")}}
 useEffect(()=>{load()},[]);
 async function patch(body:Partial<Control>){setSaving(true);setError("");try{const r=await fetch("/api/control",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save settings");setControl({mode:d.mode||control.mode,paused:Boolean(d.paused),timezone:d.timezone||control.timezone})}catch(e){setError(e instanceof Error?e.message:"Could not save settings")}finally{setSaving(false)}}
 async function checkout(plan:string){setBilling(true);setError("");try{const r=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Checkout unavailable");if(d.url)window.location.href=d.url}catch(e){setError(e instanceof Error?e.message:"Checkout unavailable")}finally{setBilling(false)}}
 async function disconnect(platform:string){if(!confirm("Disconnect "+platform+" from CYAN?"))return;setError("");try{const r=await fetch("/api/connections",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({platform})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Disconnect failed");await load()}catch(e){setError(e instanceof Error?e.message:"Disconnect failed")}}
 return <main className="page"><div className="subnav"><a href="/">← Control Center</a><span className="pill">SETTINGS</span></div>
 <section className="studiohero"><div className="eyebrow">WORKSPACE SETTINGS</div><h1>Configure how CYAN behaves.</h1><p>These controls change the cloud worker, publishing behavior and connected accounts.</p></section>
 {error&&<div className="error">{error}</div>}
 <section className="settingsGrid">
  <div className="card setting"><div className="eyebrow">AUTOMATION</div><h3>{control.paused?"Paused":"Running"} · {control.mode}</h3><p className="muted">Choose how aggressively CYAN can react to trend signals.</p><select value={control.mode} disabled={saving} onChange={e=>patch({mode:e.target.value as Control["mode"]})}><option value="conservative">Conservative</option><option value="smart">Smart</option><option value="autonomous">Autonomous</option></select><button className="btn ghost" disabled={saving} onClick={()=>patch({paused:!control.paused})}>{control.paused?"Resume cloud agent":"Pause cloud agent"}</button></div>
  <div className="card setting"><div className="eyebrow">TIMEZONE</div><h3>{control.timezone}</h3><p className="muted">Adaptive scheduling learns and recommends posting times in this workspace timezone.</p><select value={control.timezone} disabled={saving} onChange={e=>patch({timezone:e.target.value} as any)}><option>Asia/Jakarta</option><option>Asia/Singapore</option><option>Asia/Tokyo</option><option>Europe/London</option><option>Europe/Berlin</option><option>America/New_York</option><option>America/Los_Angeles</option></select></div>
  <div className="card setting"><div className="eyebrow">PUBLISHING</div><h3>Official APIs only</h3><p className="muted">CYAN never asks for social passwords and does not use browser automation.</p><span className="pill">ENFORCED</span></div>
  <div className="card setting"><div className="eyebrow">SAFETY</div><h3>Review before publish</h3><p className="muted">Generated content enters the review queue. Protected posts are excluded from automatic priority shifts.</p><span className="pill">ACTIVE</span></div>
  <div className="card setting"><div className="eyebrow">WORKSPACE</div><h3>Connected accounts</h3><p className="muted">OAuth tokens are encrypted at rest and scoped to this workspace.</p>{connections.length===0?<span className="muted">No accounts connected.</span>:connections.map(c=><div className="row" key={c.platform}><span><strong>{c.platform}</strong> · {c.accountLabel||"Connected"}</span><button className="btn ghost" onClick={()=>disconnect(c.platform)}>Disconnect</button></div>)}</div>
  <div className="card setting"><div className="eyebrow">CURRENT USAGE</div><h3>{usage?.plan?.toUpperCase()||"PLAN"}</h3><p className="muted">Today's server-enforced usage.</p>{usage&&<><div className="row"><span>Generations</span><strong>{usage.used.generations} / {usage.limits.generations}</strong></div><div className="row"><span>Publishes</span><strong>{usage.used.publishes} / {usage.limits.publishes}</strong></div><div className="row"><span>Accounts</span><strong>{usage.limits.accounts} max</strong></div></>}<span className="pill">SERVER ENFORCED</span></div>
  <div className="card setting"><div className="eyebrow">BILLING</div><h3>Plans & subscription</h3><p className="muted">Subscriptions use Stripe Checkout. Your server-side plan controls generation, publishing and account limits.</p><div className="queue">{plans.filter(p=>p.id!=="free").map(p=><div className="row" key={p.id}><span><strong>{p.name}</strong> · ${p.price}/mo<br/><small className="muted">{p.generations} generations · {p.publishes} publishes · {p.accounts} accounts</small></span><button className="btn ghost" disabled={billing} onClick={()=>checkout(p.id)}>Choose</button></div>)}</div><span className="pill">STRIPE</span></div>
  <div className="card setting"><div className="eyebrow">PRIVACY</div><h3>Workspace isolation</h3><p className="muted">Drafts, trends, usage, events and social connections are scoped to your authenticated workspace.</p><span className="pill">ISOLATED</span></div>
 </section></main>
}