"use client";
import {useEffect,useState} from "react";
type Thread={id:string;platform:string;account_label?:string;participant_label?:string;status:string;priority:string;last_message_at:string;messages:any[]};
export default function Inbox(){
 const [threads,setThreads]=useState<Thread[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/inbox?limit=50",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Inbox unavailable");setThreads(d.threads||[])}catch(e){setError(e instanceof Error?e.message:"Inbox unavailable")}finally{setLoading(false)}}
 async function update(id:string,patch:any){const r=await fetch("/api/inbox",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(!r.ok){const d=await r.json();setError(d.error||"Update failed");return}load()}
 useEffect(()=>{load()},[]);
 return <main className="page"><div className="pageHead"><div><div className="eyebrow">UNIFIED INBOX</div><h1>Conversations</h1><p className="muted">One workspace for supported social conversations. Messages appear only from verified platform connectors.</p></div><button onClick={load}>Refresh</button></div>
 <div className="card"><div className="row"><strong>{threads.length} threads</strong><span className="pill">NO FABRICATED DATA</span></div>{error&&<p className="error">{error}</p>}{loading?<p className="muted">Loading…</p>:!threads.length?<div className="empty"><h3>No conversations yet</h3><p>Inbox is ready, but no supported connector has supplied conversation data yet.</p></div>:<div className="stack">{threads.map(t=><article className="card" key={t.id}><div className="row"><div><strong>{t.participant_label||"Conversation"}</strong><div className="muted">{t.platform} · {t.account_label||"account"} · {new Date(t.last_message_at).toLocaleString()}</div></div><div className="row"><span className="pill">{t.status}</span><span className="pill">{t.priority}</span></div></div><div>{(t.messages||[]).slice(-3).map((m:any)=><p key={m.id}><strong>{m.sender_label||m.sender_type}:</strong> {m.body}</p>)}</div><div className="row"><button onClick={()=>update(t.id,{status:"pending"})}>Pending</button><button onClick={()=>update(t.id,{status:"resolved"})}>Resolve</button><button onClick={()=>update(t.id,{priority:t.priority==="urgent"?"normal":"urgent"})}>{t.priority==="urgent"?"Normal":"Urgent"}</button></div></article>)}</div>}</div></main>
}
